const router=require('express').Router(); const {auth,allow,orgScope,audit}=require('../middleware/security'); const Hostel=require('../models/Hostel'); const Payment=require('../models/Payment'); const Invoice=require('../models/Invoice'); const User=require('../models/User'); const {stkPush}=require('../services/mpesa');
router.use(auth);
router.get('/overview',async(req,res,next)=>{try{const [hostels,paid,pending,outstanding,users]=await Promise.all([Hostel.find(orgScope(req)).lean(),Payment.aggregate([{ $match:orgScope(req,{status:'verified'})},{ $group:{_id:null,total:{$sum:'$amount'},count:{$sum:1}}}]),Payment.countDocuments(orgScope(req,{status:'pending'})),Invoice.aggregate([{ $match:orgScope(req,{status:{$in:['unpaid','partial']}})},{ $group:{_id:null,total:{$sum:{$subtract:['$amount','$paidAmount']}}}}]),User.countDocuments(orgScope(req))]);const beds=hostels.reduce((a,h)=>a+h.beds,0),occ=hostels.reduce((a,h)=>a+h.occupiedBeds,0);res.json({role:req.user.role,metrics:{properties:hostels.length,beds,occupiedBeds:occ,occupancy:beds?Math.round(occ/beds*1000)/10:0,revenue:paid[0]?.total||0,transactions:paid[0]?.count||0,pendingPayments:pending,outstanding:outstanding[0]?.total||0,users}});}catch(e){next(e)}});
router.get('/payments',allow('manager','accountant','owner','platform','reception','resident'),async(req,res,next)=>{try{const q=orgScope(req,req.user.role==='resident'?{userId:req.user._id}:{ });res.json({payments:await Payment.find(q).sort({createdAt:-1}).limit(100).lean()});}catch(e){next(e)}});
router.get('/invoices',async(req,res,next)=>{try{const q=orgScope(req,req.user.role==='resident'?{userId:req.user._id}:{});res.json({invoices:await Invoice.find(q).sort({dueDate:1}).limit(100).lean()});}catch(e){next(e)}});
router.get('/properties',allow('manager','owner','platform','accountant','reception'),async(req,res,next)=>{try{res.json({hostels:await Hostel.find(orgScope(req)).sort({name:1}).lean()});}catch(e){next(e)}});
router.post('/properties',allow('owner','platform'),async(req,res,next)=>{try{const h=await Hostel.create({...req.body,organizationId:req.user.role==='platform'?req.body.organizationId:req.user.organizationId});await audit(req,'CREATE','Hostel',h._id,{name:h.name});res.status(201).json({hostel:h});}catch(e){next(e)}});

router.post('/payments/mpesa',allow('resident','manager','owner','accountant','platform'),async(req,res,next)=>{try{const {phone,amount,hostelId,invoiceId}=req.body;if(!phone||!amount)return res.status(400).json({error:'PHONE_AMOUNT_REQUIRED'});const p=await Payment.create({organizationId:req.user.organizationId,userId:req.user._id,hostelId,invoiceId,amount,method:'mpesa',status:'pending'});const r=await stkPush({phone,amount,accountRef:p._id.toString(),description:'Hosteli Zetu accommodation payment'});p.checkoutRequestId=r.CheckoutRequestID;await p.save();res.status(201).json({paymentId:p._id,customerMessage:r.CustomerMessage||'Check your phone to complete payment'});}catch(e){next(e)}});
router.post('/payments/manual',allow('accountant','manager','owner','platform'),async(req,res,next)=>{try{const {userId,hostelId,amount,method='cash'}=req.body;if(!userId||!amount)return res.status(400).json({error:'PAYMENT_FIELDS_REQUIRED'});const p=await Payment.create({organizationId:req.user.organizationId,userId,hostelId,amount,method,status:'pending'});await audit(req,'CREATE','Payment',p._id,{amount,method});res.status(201).json({payment:p});}catch(e){next(e)}});
module.exports=router;
